--!nonstrict
return {
    Idle = "Idle",
    Grounded = "Grounded",
    Sprinting = "Sprinting",
    Crouching = "Crouching",
    Sliding = "Sliding",
    Airborne = "Airborne",
    AimGliding = "AimGliding",
    BulletJumping = "BulletJumping",
    WallLatched = "WallLatched",
    WallHopping = "WallHopping",
    Rolling = "Rolling",
    AirDodging = "AirDodging",
    MeleeLocked = "MeleeLocked",
    Staggered = "Staggered",
    KnockedDown = "KnockedDown",
    GettingUp = "GettingUp",
}
