--!nonstrict
return {
    DecorBasicCrate = {
        DisplayName = "Supply Crate Decoration",
        OutputType = "Decoration",
        OutputId = "BasicCrate",
        TimeSeconds = 20,
        Costs = { Alloy = 5 },
    },
    DecorArsenalBench = {
        DisplayName = "Arsenal Bench Decoration",
        OutputType = "Decoration",
        OutputId = "ArsenalBench",
        TimeSeconds = 120,
        Costs = { Alloy = 30, Circuit = 8 },
    },
}
